// ===== SVG Icon Registry =====
var ICONS = {};
function svg(paths, viewBox) {
  return '<svg width="18" height="18" viewBox="' + (viewBox || '0 0 24 24') + '" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">' + paths + '</svg>';
}
ICONS.palette = svg('<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="3"/><path d="M12 2v4m0 12v4M2 12h4m12 0h4"/>');
ICONS.rabbit = svg('<ellipse cx="12" cy="14" rx="5" ry="6"/><ellipse cx="8" cy="7" rx="2" ry="5"/><ellipse cx="16" cy="7" rx="2" ry="5"/><circle cx="9" cy="13" r="1" fill="currentColor"/><circle cx="15" cy="13" r="1" fill="currentColor"/><path d="M10 16c1 .5 3 .5 4 0"/>');
ICONS.castle = svg('<rect x="6" y="8" width="12" height="13"/><rect x="4" y="5" width="4" height="6"/><rect x="16" y="5" width="4" height="6"/><rect x="10" y="14" width="4" height="7"/><path d="M12 14v3"/>');
ICONS.city = svg('<rect x="2" y="12" width="6" height="10"/><rect x="10" y="6" width="6" height="16"/><rect x="18" y="10" width="4" height="12"/><circle cx="13" cy="4" r="2"/>');
ICONS.cat = svg('<ellipse cx="12" cy="14" rx="7" ry="6"/><polygon points="6,9 9,5 10,9"/><polygon points="18,9 15,5 14,9"/><circle cx="9" cy="13" r="1.2" fill="currentColor"/><circle cx="15" cy="13" r="1.2" fill="currentColor"/><path d="M8 17c2 1.5 6 1.5 8 0"/><line x1="6" y1="18" x2="5" y2="21"/><line x1="18" y1="18" x2="19" y2="21"/>');
ICONS.skull = svg('<circle cx="12" cy="13" r="9"/><circle cx="9" cy="12" r="2" fill="currentColor"/><circle cx="15" cy="12" r="2" fill="currentColor"/><path d="M12 14c2 0 3 1 3 2s-1 2-3 2-3-1-3-2 1-2 3-2z"/><rect x="10" y="19" width="4" height="3" rx="1"/>');
ICONS.picture = svg('<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-4-4-6 6-3-3-5 5"/>');
ICONS.triangle = svg('<polygon points="12,2 2,22 22,22"/>');
ICONS.flower = svg('<circle cx="12" cy="12" r="3"/><circle cx="12" cy="5" r="2.5"/><circle cx="12" cy="19" r="2.5"/><circle cx="5" cy="12" r="2.5"/><circle cx="19" cy="12" r="2.5"/><circle cx="7.5" cy="7.5" r="2.5"/><circle cx="16.5" cy="7.5" r="2.5"/><circle cx="7.5" cy="16.5" r="2.5"/><circle cx="16.5" cy="16.5" r="2.5"/>');
ICONS.surreal = svg('<path d="M3 12c2-4 6-4 8-2s4 2 6 0 4-3 6-2"/><path d="M3 16c2-3 6-3 8-1s4 2 6 0 4-2 6-1"/><circle cx="9" cy="10" r="1" fill="currentColor"/><circle cx="15" cy="10" r="1" fill="currentColor"/><circle cx="12" cy="19" r="2"/>');
ICONS.crystal = svg('<circle cx="12" cy="11" r="8"/><path d="M8 19c0 2 1.5 3 4 3s4-1 4-3"/><path d="M10 19v2m4-2v2"/>');
ICONS.dragon = svg('<path d="M12 2c-3 0-5 2-5 5v2l-3 4h3l1 2c0 3 2 6 4 6s4-3 4-6l1-2h3l-3-4V7c0-3-2-5-5-5z"/><path d="M8 7h8M10 4l-1 3m6-3l1 3"/>');
ICONS.house = svg('<path d="m3 12 9-9 9 9"/><path d="M5 10v10a1 1 0 0 0 1 1h3v-7h6v7h3a1 1 0 0 0 1-1V10"/>');
ICONS.astronaut = svg('<circle cx="12" cy="10" r="7"/><path d="M12 3v2m0 10v2M5 10H3m18 0h-2"/><circle cx="12" cy="10" r="2.5" fill="currentColor"/><path d="M8 17c0 2 1.5 4 4 4s4-2 4-4"/>');
ICONS.books = svg('<rect x="4" y="6" width="4" height="14" rx="1"/><rect x="10" y="4" width="4" height="16" rx="1"/><rect x="16" y="8" width="4" height="12" rx="1"/><path d="M6 6V4m2 4V4m-2 14v2"/>');
ICONS.boat = svg('<path d="M4 16c2 3 6 4 8 4s6-1 8-4"/><path d="M2 16h20l-5-8H7L2 16z"/><line x1="12" y1="8" x2="12" y2="4"/><path d="M9 4h6l1 2H8l1-2z"/>');
ICONS.jellyfish = svg('<path d="M6 12c0-4 2.5-7 6-7s6 3 6 7"/><path d="M6 12c-2 0-3 2-3 3s1 3 3 3"/><path d="M18 12c2 0 3 2 3 3s-1 3-3 3"/><path d="M8 15v4m4-4v5m4-4v4"/><circle cx="6" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="11" r="1.2" fill="currentColor"/><circle cx="18" cy="12" r="1" fill="currentColor"/>');
ICONS.bamboo = svg('<line x1="12" y1="2" x2="12" y2="22"/><path d="M5 9l7-3 7 3"/><path d="M5 15l7-3 7 3"/><path d="M8 4l4 2 4-2"/><path d="M8 20l4-2 4 2"/>');
ICONS.bulb = svg('<path d="M9 18h6m-5 3h4m-6-6c0-3 1.5-5 4-6s4 3 4 6c0 2-1 3-2 4H9c-1-1-2-2-2-4z"/>');
ICONS.dice = svg('<rect x="4" y="4" width="16" height="16" rx="2"/><circle cx="9" cy="9" r="1" fill="currentColor"/><circle cx="15" cy="9" r="1" fill="currentColor"/><circle cx="9" cy="15" r="1" fill="currentColor"/><circle cx="15" cy="15" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/>');
ICONS.clipboard = svg('<rect x="7" y="3" width="10" height="4" rx="1"/><rect x="5" y="7" width="14" height="14" rx="2"/><line x1="9" y1="12" x2="15" y2="12"/><line x1="9" y1="16" x2="13" y2="16"/>');
ICONS.heart = svg('<path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>');
ICONS.pencil = svg('<path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"/>');
ICONS.camera = svg('<rect x="2" y="6" width="20" height="15" rx="3"/><circle cx="12" cy="13" r="5"/><path d="M17 6l-1-3H8L7 6"/>');
ICONS.tag = svg('<path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"/><line x1="7" y1="7" x2="7.01" y2="7"/>');
ICONS.clapper = svg('<rect x="2" y="6" width="20" height="14" rx="2"/><path d="M2 10h20"/><path d="M7 3l-2 4m6-4l-2 4m6-4l-2 4m6-4l-2 4"/>');
ICONS.play = svg('<polygon points="6 3 20 12 6 21 6 3"/>');
ICONS.sparkle = svg('<path d="M12 2l1.5 6.5L20 12l-6.5 3.5L12 22l-1.5-6.5L4 12l6.5-3.5L12 2z"/><circle cx="12" cy="12" r="2"/>');
ICONS.book = svg('<path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20"/><path d="M12 2v20"/>');
ICONS.burst = svg('<polygon points="12,2 14,9 21,9 15.5,14 18,22 12,17 6,22 8.5,14 3,9 10,9"/><circle cx="12" cy="12" r="2" fill="currentColor"/>');
ICONS.folder = svg('<path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2v11z"/>');
ICONS.moon = svg('<path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>');
ICONS.sun = svg('<circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>');
ICONS.plus = svg('<line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>');
ICONS.trash = svg('<polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/><line x1="10" y1="11" x2="10" y2="17"/><line x1="14" y1="11" x2="14" y2="17"/>');
ICONS.globe = svg('<circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/>');
ICONS.warning = svg('<path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>');
ICONS.check = svg('<polyline points="20 6 9 17 4 12"/>');
ICONS.ruler = svg('<path d="M2 12l10-10 10 10-10 10z"/><line x1="7" y1="12" x2="10" y2="9"/><line x1="5" y1="10" x2="8" y2="7"/>');
ICONS.target = svg('<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/><line x1="12" y1="2" x2="12" y2="4"/><line x1="12" y1="20" x2="12" y2="22"/>');
ICONS.bolt = svg('<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>');
ICONS.pause = svg('<rect x="6" y="4" width="4" height="16" rx="1"/><rect x="14" y="4" width="4" height="16" rx="1"/>');

// ===== State =====
var state = {
  mode: 'generate',           // 'generate' | 'edit'
  model: 'hd',                // 'hd' | 'genius' | 'super-genius'
  preference: 'quality',      // 'speed' | 'quality'
  geniusStyle: 'classic',     // 'classic' | 'anime' | 'photo' | 'cinema' | 'graphics'
  shape: 2,                   // 1..5
  style: 'cyberpunk-generator',
  yeNewe: false,
  currentImage: null,         // { dataUrl, prompt, inputs }
  originalPrompt: '',         // for enhance undo
  enhancedPrompt: '',         // enhanced version
  isEnhancing: false,
  history: [],                // [{dataUrl, prompt}]
  historyIndex: -1,
  isGenerating: false,
};

// ===== Styles config =====
// ===== Hallucination Shield style configs (Schema 3.0) =====
var STYLE_CONFIGS = {
  "Cute Creature Generator": {"primary_subject_grounding":"Exactly 1 primary creature. It is a bipedal, round-bodied fluffball. Both feet (exactly 2) are planted flat on a soft, moss-covered log, shoulder-width apart. The left paw (exactly 1) grips a tiny wooden honey spoon, resting against its plush belly. The right paw (exactly 1) is raised to ear-level, open-palmed in a friendly wave. Spine is curved into a relaxed 'C' shape. Head is tilted 20 degrees to the right.","secondary_figures":"No secondary figures. The creature is completely isolated to prevent morphing.","depth_layers":"F: Out-of-focus oversized daisies and clovers, occupying the bottom 20% of the frame, 5 inches in front of the creature's toes. M: The creature itself, fully in sharp focus. B: A distant rolling green hill under a soft pastel rainbow, separated by atmospheric haze, located 100 meters behind the creature.","physics_gravity":"The creature's weight causes a subtle 0.5-inch indentation in the soft moss beneath both feet. The honey spoon has a single viscous drop of honey suspended mid-drip, acting as a static time-freeze anchor.","lighting_shadow_logic":"A single warm, diffused sunlight source from top-right. The creature casts a distinct, soft-edged drop shadow directly beneath its feet onto the moss. The raised right paw casts a secondary soft shadow across its own forehead.","color_texture_binding":"The creature's fur is a matte mint green (#98FF98) with a soft, fuzzy texture. The creature's inner ears and cheeks are a pastel pink (#FFB6C1). The wooden spoon is a warm maple (#C19A6B) with a glossy lacquer finish. Crucial: The pink cheeks are strictly bounded to the round areas under the eyes; pink must NOT bleed into the green fur or the background.","perspective_lens":"Eye-level perspective, shot on a 50mm prime lens. Full-body shot, cropping just below the creature's knees and just above the ears. Horizon line is placed exactly at the creature's belly button.","style_render":"Pixar-style 3D render, Cinema 4D, soft global illumination, 8k, clay-like shaders with subsurface scattering on the ears.","hard_stops":"No sharp teeth, no realistic claws, no tall/slender humanoid proportions, no sad or crying expressions, no dark shadows, no extra limbs beyond the specified 2 feet and 2 paws.","count_verification":"Exactly 1 creature, exactly 2 visible feet, exactly 2 visible paws, exactly 1 spoon, exactly 1 background hill, exactly 0 other creatures."},
  "Fantasy World Generator": {"primary_subject_grounding":"Exactly 1 central figure: a lone archmage. Both feet (exactly 2) are shoulder-width apart on a fractured stone balcony. The left hand (exactly 1) grips the middle section of a vertically planted oak staff, knuckles wrapped around the gnarled wood. The right hand (exactly 1) is extended forward at a 45-degree angle, palm open, fingers spread wide, channeling energy.","secondary_figures":"No secondary figures. The archmage is isolated to prevent fusion.","depth_layers":"F: Jagged, broken stone railing of the balcony, occupying the bottom 15%, out of focus. M: The archmage, fully in focus. B: A massive expanse of floating islands with cascading waterfalls plummeting into a glowing abyss, heavily diffused by magical mist, 500 meters behind the balcony.","physics_gravity":"The archmage's weight is firmly planted; his leather boots have visible cracks forming in the stone beneath them under the stress of his stance. The staff is braced vertically, bearing the downward force of his weight.","lighting_shadow_logic":"Magical golden-hour sunlight from the left. The archmage's silhouette casts a sharp, elongated shadow across the balcony floor to the right. The staff casts a distinct vertical shadow line dividing the balcony. The right hand's palm emits a cool cyan glow, casting a secondary, faint blue shadow downwards onto his own robe.","color_texture_binding":"The archmage's robes are a deep, matte violet (#4B0082) with gold-threaded runes. The staff is rough, weather-beaten #8B4513 oak. The floating islands are desaturated teal (#2F4F4F) with bright cyan (#00FFFF) waterfalls. Crucial: The cyan palm-glow ONLY affects the right hand and the front fold of the robe; the background islands remain strictly cool teal without cyan spillage.","perspective_lens":"Low-angle hero shot, 24mm wide-angle lens (minimal distortion). Full-body shot, cropped at the archmage's shins and extending 10 feet above his head to show the massive sky. Horizon line is placed below the balcony, emphasizing the drop.","style_render":"Epic digital matte painting, oil on canvas texture, Unreal Engine 5 Nanite geometry, volumetric fog.","hard_stops":"No sci-fi elements, no neon lights, no modern clothing, no extra hands (exactly 2 visible), no floating islands in the foreground (must be background only), no dragons.","count_verification":"Exactly 1 archmage, exactly 2 visible feet, exactly 2 visible hands, exactly 1 oak staff, exactly 4 visible floating islands, exactly 0 additional creatures."},
  "Cyberpunk Generator": {"primary_subject_grounding":"Exactly 1 cyborg. Both boots (exactly 2) are planted flat on a rain-slicked asphalt alleyway. The right shoulder (exactly 1) leans heavily against a corrugated steel wall. The right hand (exactly 1) is pressed flat against the wet wall at shoulder-height, palm spread. The left hand (exactly 1) firmly grips the polymer grip of a semi-automatic pistol, barrel pointed directly at the ground.","secondary_figures":"No secondary figures. The cyborg is completely isolated to prevent limb fusion.","depth_layers":"F: A metal grating and a steam vent out of focus, occupying the bottom 10%. M: The cyborg leaning against the wall, fully in focus. B: A towering cityscape of neon-lit skyscrapers, heavily obscured by volumetric acid-rain fog, 100 meters behind the cyborg.","physics_gravity":"The cyborg's weight is distributed 60% on the left boot and 40% on the right. The left boot has a visible 0.2-inch puddle of water rippling around its sole. The leaning shoulder creates visible compression against the corrugated steel.","lighting_shadow_logic":"A single harsh magenta neon sign (#FF00FF) mounted 15 feet above casts harsh downward light. The cyborg's head casts a sharp, tall shadow 6 feet behind him onto the alley floor. The pistol casts a distinct secondary shadow forward. Crucial: Two distinct, non-overlapping shadow sources exist.","color_texture_binding":"The cyborg's trench coat is a glossy #1A1A1A pitch black. The cybernetic left arm is raw #C0C0C0 silver chrome with exposed red #B22222 wiring. The pistol is matte #2F4F4F with a cyan #00FFFF ammo counter. Crucial: The magenta neon light ONLY highlights the right side of the coat; the cyan ammo counter stays strictly bounded to the pistol slide.","perspective_lens":"Dutch angle (15-degree tilt), shoulder-level perspective. Shot on a 35mm anamorphic lens. Mid-shot, cropping at the cyborg's knees and just above his head.","style_render":"Photorealistic 8k, Octane Render, ray-traced reflections, volumetric fog, high contrast, gritty film grain.","hard_stops":"No organic animals, no medieval weapons, no sunlit scenes, no warm/pastel colors, no extra mechanical limbs beyond the 2 biological arms and 2 legs.","count_verification":"Exactly 1 cyborg, exactly 2 visible boots, exactly 2 visible hands, exactly 1 pistol, exactly 1 neon sign, exactly 0 other humans."},
  "Anime Portrait Generator": {"primary_subject_grounding":"Exactly 1 female subject. Head, neck, and shoulders are visible in a bust-framing. The chin is resting directly on the interlocked fingers of exactly 2 hands, elbows planted firmly on a solid wooden table surface (out of frame at the bottom edge). Face is turned 30-degrees to the left.","secondary_figures":"No secondary figures.","depth_layers":"F: Out-of-focus wooden table surface and the character's forearms. M: The character's face, hair, and shoulders, fully in sharp focus. B: A soft gradient of sunset pinks and oranges, completely flat, with no distinct objects to prevent background bleeding.","physics_gravity":"The weight of the head is fully supported by the interlocked hands; slight compression of the cheeks is visible where the fingers meet the skin.","lighting_shadow_logic":"Soft, diffuse celestial rim lighting from top-left, creating a distinct sharp rim-light on the hair. A soft, low-contrast fill light from the right to eliminate harsh under-eye shadows.","color_texture_binding":"The hair is a solid, deep royal blue (#000080) with sharp, cel-shaded white (#FFFFFF) highlights on the top strands. The skin is pale ivory (#FFFDD0) with a distinct rose-pink (#FF69B4) airbrush gradient on the cheeks and nose bridge. The eyes are vivid emerald (#50C878) with distinct white catchlights. Crucial: The cheek blush MUST NOT bleed into the hair or forehead; it is strictly confined to the lower cheekbones.","perspective_lens":"Face-level perspective, 85mm telephoto lens (flattering compression). Bust-shot, cropping just below the collarbones and just above the hairline.","style_render":"Digital cel-shading, clean vector-like inking, Makoto Shinkai color palette, 4k, soft bloom on highlights.","hard_stops":"No photorealistic skin pores, no 3D polygon artifacts, no shadows under the nose (keep it stylized), no realistic eyeball veins, no glossy/wet skin textures.","count_verification":"Exactly 1 head, exactly 2 visible shoulders, exactly 2 visible hands (interlocked), exactly 2 eyes visible, exactly 0 other figures."},
  "Old Drawing Generator": {"primary_subject_grounding":"Exactly 1 anatomical study: a human ribcage and skull. The skull is placed directly on a wooden desk surface, resting on its mandible (chin). The ribcage is situated 6 inches behind the skull, leaning slightly backward against a stack of aged books.","secondary_figures":"No secondary figures. Only bones and books.","depth_layers":"F: A single charcoal pencil and a crumpled eraser, lying flat on the desk, 4 inches in front of the skull. M: The skull and the ribcage, fully in focus. B: A blank, textured parchment background (wall) with zero objects, 3 feet behind the desk.","physics_gravity":"The skull rests with its full weight on the desk; the bone contacts the wood with no gap. The ribcage is slightly sunken into the dusty surface, indicating static weight.","lighting_shadow_logic":"A single harsh candlelight source from front-left (45 degrees). The skull casts a deep, elongated shadow toward the back-right of the desk. The ribcage casts a secondary overlapping shadow onto the books behind it.","color_texture_binding":"The entire drawing is strictly monochromatic sepia (#8B4513) and parchment ivory (#F5DEB3). The pencil is charcoal black (#36454F). The paper texture has a distinct, visible grain. Crucial: No color saturation exists; everything must stay within the sepia/black range.","perspective_lens":"Eye-level perspective, flat orthographic projection (minimal distortion). Full frame of the desk, cropped to show the entire skull and the left half of the ribcage.","style_render":"Silverpoint and cross-hatching pen-and-ink, visible paper grain, deckled edges, 19th-century scientific illustration aesthetic.","hard_stops":"No color (strictly monochrome), no smooth airbrushing (use hatch lines), no shiny gloss, no digital gradients, no human figures.","count_verification":"Exactly 1 skull, exactly 1 ribcage, exactly 1 pencil, exactly 3 books, exactly 0 living subjects."},
  "Renaissance Painting Generator": {"primary_subject_grounding":"Exactly 1 noblewoman. Seated in a high-backed wooden armchair. Both feet (exactly 2) are flat on a stone floor, crossed at the ankles. The right arm (exactly 1) rests on the wooden armrest, hand holding a folded fan. The left arm (exactly 1) rests delicately on her lap, fingers interlaced.","secondary_figures":"No secondary figures.","depth_layers":"F: The ornate wooden armrest and the edge of her velvet dress, occupying the bottom 20%. M: The noblewoman, fully in focus, occupying 70% of the frame. B: A dark, classical column and a heavy velvet drape, shrouded in deep shadow, 15 feet behind the chair.","physics_gravity":"The woman's weight is firmly planted in the chair; her feet bear weight evenly on the stone, causing her dress to pool naturally around the ankles. The chair's legs are physically grounded to the stone floor.","lighting_shadow_logic":"Single window light source from top-left (north light), creating a classic Rembrandt triangle lighting pattern on the left cheek. The chair casts a massive, dark, impenetrable shadow directly behind it onto the column.","color_texture_binding":"The dress is a deep, rich crimson (#800020) with woven gold (#D4AF37) thread. The chair is dark #3B2F2F mahogany. The skin is pale ivory (#FFFDD0). The background column is #4A4A4A stone. Crucial: The red of the dress MUST NOT reflect onto the ivory skin; the skin remains strictly cool-toned to separate it from the fabric.","perspective_lens":"Eye-level perspective, 50mm prime lens. Three-quarter bust/waist shot, cropping at the noblewoman's knees and just above the top of her head.","style_render":"Oil on linen canvas, smooth sfumato blending, thick impasto on the dress details, aged varnish patina, 8k.","hard_stops":"No modern clothing, no direct eye contact with camera (gaze is averted), no harsh LED lighting, no abstract geometry, no extra hands (exactly 2 visible).","count_verification":"Exactly 1 noblewoman, exactly 2 visible hands, exactly 2 visible feet, exactly 1 chair, exactly 1 fan, exactly 0 background figures."},
  "Abstract Painting Generator": {"primary_subject_grounding":"No human figures, animals, or recognizable objects. The canvas is entirely occupied by geometric and organic 2D shapes. No single subject exists to ground; the entire flat canvas is the subject.","secondary_figures":"Not applicable. This is a non-figurative 2D plane.","depth_layers":"Strictly 2D flat plane. No foreground, midground, or background depth. All elements exist on the same singular, flat Cartesian plane. Zero perspective distortion.","physics_gravity":"No gravity applies. Shapes are freely floating in the 2D space, not anchored to any surface.","lighting_shadow_logic":"Completely flat, even, museum-grade lighting. Zero shadows, zero highlights, zero volumetric effects. Pure diffuse light hitting a 2D surface.","color_texture_binding":"Only 5 colors allowed: Primary Red #FF0000, Primary Yellow #FFFF00, Primary Blue #0000FF, Absolute Black #000000, and Canvas White #FFFFFF. Shapes are bounded by sharp, straight lines or perfect mathematical curves. Crucial: No blending between colors; edges must be sharp and crisp. Black lines strictly divide colored blocks.","perspective_lens":"Front-facing orthographic projection. No lens distortion. The canvas is viewed straight-on, filling the entire frame perfectly.","style_render":"Flat vector art, De Stijl aesthetic, Bauhaus geometry, matte paint finish, no texture.","hard_stops":"No gradients, no 3D depth, no shading, no recognizable objects (cubes, spheres, faces), no painterly brush strokes (must be crisp blocks).","count_verification":"Exactly 0 figures, exactly 0 recognizable objects, exactly 5 colors used, exactly 0 shadows."},
  "Impressionism Painting Generator": {"primary_subject_grounding":"Exactly 1 focal point: a cluster of water lilies floating on a pond. The lilies are physically resting on the surface of the water. A wooden rowboat is moored to a wooden post in the midground, grounded by the water's buoyancy.","secondary_figures":"No human figures are present. Only flora and a boat.","depth_layers":"F: Out-of-focus lily pads and blurred reflections in the water, occupying the bottom 30% of the frame. M: The central cluster of blooming water lilies, painted with broken brushstrokes. B: A treeline of tall poplar trees and a hazy sky, heavily diffused and merged with the water at the horizon line.","physics_gravity":"The lilies float without sinking; their weight is displaced by the water. The wooden boat rocks gently, causing tiny ripple lines in the water's surface.","lighting_shadow_logic":"Soft, dappled natural daylight filtering through the poplar leaves. The shadows are not black; they are painted in complementary purple and blue tones. No harsh cast shadows exist.","color_texture_binding":"The water is a shimmering mix of cerulean blue #007BA7 and lavender #E6E6FA. The lilies are soft pink #FFB6C1 with yellow #FFD700 centers. The trees are a mix of moss green #8A9A5B. Crucial: The pink of the lilies is broken into separate brushstrokes of red and white, NOT blended into a solid color. The water reflections strictly mirror the sky's broken colors.","perspective_lens":"Slightly low-angle perspective at water-level. Shot on an 85mm lens with soft focus. Horizon line is placed high, occupying the top 20% of the frame.","style_render":"Thick, broken brushstrokes, wet-on-wet painting, visible unblended adjacent complementary colors, canvas texture visible.","hard_stops":"No hard outlines, no pure black paint (use darks/blues), no photorealism, no crisp edges, no solid flat color areas.","count_verification":"Exactly 1 cluster of lilies, exactly 1 boat, exactly 0 human figures, exactly 5 visible poplar trunks."},
  "Surreal Graphics Generator": {"primary_subject_grounding":"Exactly 1 primary object: a massive, melting pocket watch. The watch is draped over the horizontal branch of a dead, gnarled tree. The watch's weight wraps the leather band completely around the branch, physically grounded by gravity pulling the pocket watch downward.","secondary_figures":"No secondary figures or creatures. Only the tree and the watch.","depth_layers":"F: A single dead fish lying on a cracked desert floor, 2 feet in front of the tree, out of focus. M: The gnarled tree and the melting watch, fully in focus. B: A flat, infinite, desaturated blue sky with no clouds, extending to a stark, sharp horizon line.","physics_gravity":"The melting watch drips downward in a viscous manner, obeying gravity. The tree's roots are physically anchored into the cracked desert soil.","lighting_shadow_logic":"Impossible lighting: harsh high-noon sun from directly above, casting no shadows except directly beneath objects. The watch casts a soft, circular puddle-shadow on the ground directly beneath it.","color_texture_binding":"The watch is a shiny gold #DAA520 with a white #F5F5DC dial. The tree is an ashen grey #B2BEB5. The desert floor is a bleached bone #F5F5DC. The sky is a deep surreal blue #0B3B60. Crucial: The gold reflection does NOT bleed into the sky; the sky is entirely uniform.","perspective_lens":"Eye-level perspective, shot on a 35mm wide-angle lens. Wide establishing shot, showing the entire tree and the vast flat desert.","style_render":"Hyper-detailed oil painting, airbrushed 70s sci-fi aesthetic, sharp focus, extreme clarity.","hard_stops":"No standard physics, no realistic clouds (sky is flat), no human figures, no everyday objects (besides watch), no soft/blurred edges (keep it sharp).","count_verification":"Exactly 1 tree, exactly 1 melting watch, exactly 1 dead fish, exactly 0 human figures."},
  "3d Objects Generator": {"primary_subject_grounding":"Exactly 1 primary object: a highly polished chrome sphere. The sphere is physically resting perfectly at the center of a large, seamless, glossy white pedestal. The bottom point of the sphere touches the pedestal with zero gap (perfect contact point).","secondary_figures":"No secondary figures or objects. The scene contains only the sphere, the pedestal, and the background.","depth_layers":"None. The object is the only element. M: The chrome sphere and the top of the white pedestal, in sharp focus. B: A seamless, gradient gray (from #505050 to #1A1A1A) studio backdrop, 10 feet behind the pedestal.","physics_gravity":"The sphere's full weight presses down on the contact point. The pedestal is a solid block; no indentation occurs, but the contact point is the sharpest focal point to emphasize physical contact.","lighting_shadow_logic":"Studio softbox lighting: one large key light from top-left, one rim light from back-right. The sphere casts a crisp, circular drop shadow directly onto the white pedestal beneath it. The pedestal casts a soft, diffused shadow onto the grey background.","color_texture_binding":"The sphere is strictly chrome #C0C0C0 with an HDRI environmental reflection showing soft studio umbrellas. The pedestal is pure glossy white #FFFFFF with a subtle Fresnel reflection of the sphere. Crucial: The chrome reflection strictly shows the environment, not a distorted self-reflection of its own color.","perspective_lens":"Isometric camera angle (30-degree tilt). Shot on a 90mm macro lens. The object is centered, occupying 70% of the frame.","style_render":"C4D physical render, 8k, ray-traced global illumination, flawless UV mapping, 16-bit color depth.","hard_stops":"No textures with tiling errors, no chromatic aberration, no background clutter, no second objects, no soft/noisy shadows (keep shadows sharp/crisp).","count_verification":"Exactly 1 chrome sphere, exactly 1 white pedestal, exactly 1 background gradient, exactly 0 other objects."}
};

var STYLES = [
  { id: 'text2img',                name: 'AI Image',       svg: ICONS.palette, gradient: 'linear-gradient(135deg,#667eea,#764ba2)', modifier: '', configName: null },
  { id: 'cute-creature-generator', name: 'Cute Creature',  svg: ICONS.rabbit, gradient: 'linear-gradient(135deg,#f093fb,#f5576c)', modifier: 'cute adorable creature, fluffy, big eyes, kawaii style', configName: 'Cute Creature Generator' },
  { id: 'fantasy-world-generator', name: 'Fantasy World',  svg: ICONS.castle, gradient: 'linear-gradient(135deg,#4facfe,#00f2fe)', modifier: 'fantasy world, magical, epic landscape, mystical atmosphere', configName: 'Fantasy World Generator' },
  { id: 'cyberpunk-generator',     name: 'Cyberpunk',      svg: ICONS.city, gradient: 'linear-gradient(135deg,#fa709a,#fee140)', modifier: 'cyberpunk, neon lights, futuristic city, sci-fi, dystopian', configName: 'Cyberpunk Generator' },
  { id: 'anime-portrait-generator',name: 'Anime Portrait', svg: ICONS.cat, gradient: 'linear-gradient(135deg,#a18cd1,#fbc2eb)', modifier: 'anime portrait, manga style, detailed eyes, cel shaded', configName: 'Anime Portrait Generator' },
  { id: 'old-drawing-generator',   name: 'Old Drawing',    svg: ICONS.skull, gradient: 'linear-gradient(135deg,#d4b483,#8b6f47)', modifier: 'old drawing, sketch, vintage illustration, sepia', configName: 'Old Drawing Generator' },
  { id: 'renaissance-generator',   name: 'Renaissance',    svg: ICONS.picture, gradient: 'linear-gradient(135deg,#cb9d06,#800020)', modifier: 'renaissance painting, classical art, oil painting', configName: 'Renaissance Painting Generator' },
  { id: 'abstract-generator',      name: 'Abstract',       svg: ICONS.triangle, gradient: 'linear-gradient(135deg,#ff0000,#0000ff)', modifier: 'abstract painting, geometric, bauhaus, de stijl', configName: 'Abstract Painting Generator' },
  { id: 'impressionism-generator', name: 'Impressionism',  svg: ICONS.flower, gradient: 'linear-gradient(135deg,#8a9a5b,#007ba7)', modifier: 'impressionism, broken brushstrokes, monet style', configName: 'Impressionism Painting Generator' },
  { id: 'surreal-graphics-generator', name: 'Surreal',     svg: ICONS.surreal, gradient: 'linear-gradient(135deg,#0b3b60,#daa520)', modifier: 'surreal, dreamlike, impossible physics, dali style', configName: 'Surreal Graphics Generator' },
  { id: '3d-objects-generator',    name: '3D Objects',     svg: ICONS.crystal, gradient: 'linear-gradient(135deg,#c0c0c0,#505050)', modifier: '3d render, chrome, studio lighting, product shot', configName: '3d Objects Generator' },
];

// ===== Shapes config (id -> resolution) =====
var SHAPES = {
  1: { resolution: '1920x1080', w: 38, h: 20 },  // wide landscap
  2: { resolution: '1280x720', w: 28, h: 20 },  // landscape  (default)
  3: { resolution: '1080x1080', w: 24, h: 24 },  // square
  4: { resolution: '720x1280', w: 20, h: 28 },  // portrait
  5: { resolution: '1080x1920', w: 20, h: 38 },  // tall portrait
};
